# production:
#   adapter: postgresql
#   database: <%= ENV['APP_DB'] %>
#   username: <%= ENV['APP_DB_USER'] %>
#   password: <%= ENV['APP_DB_PASSWORD'] %>
#   host: <%= ENV['APP_DB_HOST'] %>
#   pool: 15

development:
  adapter: postgresql
  database: <%= ENV['APP_DB'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  pool: 15